name: "gh-action_releasability"
description: "gh-action client for ops-releasability checks"
author: "RE Team"
inputs:
  ignore-failure:
    description: Optional, do not fail the gh-action in case of pre-commit check failure
    required: false
    default: "false"
outputs:
  status:
    description: Provide the exit code returned by pre-commit run command
  logs:
    description: Logs from the pre-commit run command
runs:
  using: "docker"
  image: "Dockerfile"
