name: "gh-action_releasability"
description: "gh-action client for ops-releasability checks"
author: "RE Team"
inputs:
  ignore-failure:
    description: Optional, do not fail the gh-action in case of failure in releasability checks
    required: false
    default: "false"
  organization:
    description: GitHub organization name
    required: true
  repository:
    description: GitHub repository name
    required: true
  branch:
    description: Branch name
    required: true
  version:
    description: The version to check
    required: true
  commit-sha:
    description: The GitHub commit SHA to use
    required: true
  releasabily-env:
    description: For development purposes, the environment to use (prod, staging or dev). Defaults to production.
    required: false
    default: prod
outputs:
  status:
    description: Provide the exit code returned by the releasability checks
    value: ${{ steps.checks.outputs.status }}
  logs:
    description: Logs from releasability checks
    value: ${{ steps.checks.outputs.logs }}
  releasabilityCheckDependencies:
    description: Result from releasability check CheckDependencies
    value: ${{ steps.checks.outputs.releasabilityCheckDependencies }}
  releasabilityQA:
    description: Result from releasability check QA
    value: ${{ steps.checks.outputs.releasabilityQA }}
  releasabilityJira:
    description: Result from releasability check Jira
    value: ${{ steps.checks.outputs.releasabilityJira }}
  releasabilityWhiteSource:
    description: Result from releasability check WhiteSource
    value: ${{ steps.checks.outputs.releasabilityWhiteSource }}
  releasabilityCheckPeacheeLanguagesStatistics:
    description: Result from releasability check CheckPeacheeLanguagesStatistics
    value: ${{ steps.checks.outputs.releasabilityCheckPeacheeLanguagesStatistics }}
  releasabilityQualityGate:
    description: Result from releasability check QualityGate
    value: ${{ steps.checks.outputs.releasabilityQualityGate }}
  releasabilityParentPOM:
    description: Result from releasability check ParentPOM
    value: ${{ steps.checks.outputs.releasabilityParentPOM }}
  releasabilityGitHub:
    description: Result from releasability check GitHub
    value: ${{ steps.checks.outputs.releasabilityGitHub }}
  releasabilityCheckManifestValues:
    description: Result from releasability check CheckManifestValues
    value: ${{ steps.checks.outputs.releasabilityCheckManifestValues }}

runs:
  using: "composite"
  steps:
    - id: setup_python
      name: Setup python
      uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
      with:
        python-version: "3.10"
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@4fc4975a852c8cd99761e2de1f4ba73402e44dd9 # v4.0.3
      env:
        prod: "064493320159"
        staging: "308147251410"
        dev: "597611216173"
      with:
        aws-region: eu-central-1
        role-to-assume: "arn:aws:iam::${{ env[inputs.releasabily-env] }}:role/ReleasbilityChecksCICDRole"
    - name: Install requirements
      run: |
        pip install pipenv
        pipenv install
      shell: bash
      working-directory: ${{ github.action_path }}
    - name: Trigger releasability checks
      id: checks
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        # Validate inputs before using them
        if [[ ! "${{ inputs.organization }}" =~ ^[a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9]$ ]]; then
          echo "::error::Invalid organization name format"
          exit 1
        fi
        if [[ ! "${{ inputs.repository }}" =~ ^[a-zA-Z0-9][a-zA-Z0-9._\s-]*[a-zA-Z0-9]$ ]] || [[ "${{ inputs.repository }}" =~ \.git$ ]]; then
          echo "::error::Invalid repository name format. Repository names must:"
          echo "  - Start with an alphanumeric character"
          echo "  - End with an alphanumeric character"
          echo "  - Can contain alphanumeric characters, dots, underscores, spaces, and hyphens"
          echo "  - Cannot end with .git"
          exit 1
        fi
        if [[ ! "${{ inputs.branch }}" =~ ^[a-zA-Z0-9][a-zA-Z0-9/_.-]*$ ]]; then
          echo "::error::Invalid branch name format. Branch names must:"
          echo "  - Start with an alphanumeric character"
          echo "  - Can contain alphanumeric characters, forward slashes, dots, and hyphens"
          echo "  - Examples: master, feat/tom/build-1234, release/1.0.0"
          exit 1
        fi
        if [[ ! "${{ inputs.version }}" =~ ^([a-zA-Z0-9]+-)?[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9]+)?(\.[0-9]+)?$ ]]; then
          echo "::error::Invalid version format. Version must follow pattern: [ProjectName-]Major.Minor.Patch[-Mx][.+]BuildNumber"
          echo "  Examples: sqs-2025.4.0.111749, 10.1.1.1234, project-1.0.0-beta.123"
          exit 1
        fi
        if [[ ! "${{ inputs.commit-sha }}" =~ ^[a-fA-F0-9]{7,40}$ ]]; then
          echo "::error::Invalid commit SHA format. Must be a valid Git commit hash (7-40 hexadecimal characters)"
          exit 1
        fi
        if [[ ! "${{ inputs.releasabily-env }}" =~ ^(prod|staging|dev)$ ]]; then
          echo "::error::Invalid environment specified"
          exit 1
        fi

        pipenv run releasability
      env:
        INPUT_ORGANIZATION: ${{ inputs.organization }}
        INPUT_REPOSITORY: ${{ inputs.repository }}
        INPUT_BRANCH: ${{ inputs.branch }}
        INPUT_VERSION: ${{ inputs.version }}
        INPUT_COMMIT_SHA: ${{ inputs.commit-sha}}
        PYTHONUNBUFFERED: "1" # that way logs are printed live
    - name: Print execution
      run: |
        echo "${{ steps.checks.outputs.logs }}"
        echo "Exit code: ${{ steps.checks.outputs.status }}"
      shell: bash
    - name: Check status and fail if necessary
      if: ${{ inputs.ignore-failure == 'false' && steps.checks.outputs.status != 0 }}
      run: |
        echo "::error:: Releasability checks reported some errors."
        exit 1
      shell: bash
